TugasKelompok1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('accounts/', include('accounts.urls')),
    path('feedback/', include('main.urls')),
    path('kisahcovid/', include('kisahCovid.urls')),
    path('volunteer/',include('Vol.urls')),
    path('donasi/',include('donasi.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vol/urls.py
from django.urls import path

from . import views

app_name = 'Vol'

urlpatterns = [
    path('', views.home, name='home'),
    path('tambah-rumah-sakit/', views.tambahRumahSakit, name='rumahsakit'),
    path('tambah-volunteer/<int:id>', views.volunteer, name='volunteer'),
]

landingpage/urls.py
from django.urls import path

from . import views

app_name = 'landingpage'

urlpatterns = [
    path('', views.index, name='index'),
    path('get-contact/', views.get_contact, name='getcontact'),
    path('post-contact/<str:name>/<str:email>/<str:phone>/<str:age>/<str:description>/', views.post_contact),
    
]

landingpage/models.py
from django.db import models

# Create your models here.

class ContactUs(models.Model):
  name = models.CharField(max_length=128)
  email = models.CharField(max_length=128)
  phone = models.CharField(max_length=128)
  age = models.CharField(max_length=128)
  description = models.TextField()

  def __str__(self):
        return self.name + ", " + self.age

class KasusProvinsi(models.Model):
    provinsi = models.CharField(max_length=50)
    kasus_positif = models.IntegerField()
    kasus_sembuh = models.IntegerField()
    kasus_meninggal = models.IntegerField()

    def __str__(self):
        return self.provinsi

landingpage/forms.py
from django import forms
from .models import ContactUs

class ContactForm(forms.ModelForm):
  class Meta:
    model = ContactUs
    fields = '__all__'

landingpage/views.py
import requests
from django.shortcuts import render
from django.http import JsonResponse

from .helper import kasus_provinsi_helper

# Models
from .models import KasusProvinsi, ContactUs

# Forms
from .forms import ContactForm

def index(request):
    response = requests.get('https://api.kawalcorona.com/indonesia/provinsi')
    data = response.json()
    kasus_provinsi_helper(data)
    data_semua_kasus = KasusProvinsi.objects.all()

    form = ContactForm()
    jumlah_input = ContactUs.objects.count()
    context = {
        'semua_data' : data_semua_kasus,
        'title' : 'Silahkan isi data',
        'form': form,
        'jumlah_input' : jumlah_input
    }
    return render(request, 'index.html', context)
   
def get_contact(request):
    json = list(ContactUs.objects.values())
    json.reverse()
    print(json)

    return JsonResponse({'data' : json}, safe=False)

def post_contact(request, name, email, phone, age, description):

    if (request.user.is_authenticated):
        form = ContactUs(name = name, email = email, phone = phone, age = age, description = description)   
        form.save()
    
    return get_contact(request)

landingpage/templates/thankyou.html
<html lang="en">

{% extends "base.html" %}

{% block content %}

<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href='https://fonts.googleapis.com/css?family=Lato:300,400|Montserrat:700' rel='stylesheet' type='text/css'>
	<style>
		@import url(//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css);
		@import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);
	</style>
	<link rel="stylesheet" href="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/default_thank_you.css">
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/jquery-1.9.1.min.js"></script>
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/html5shiv.js"></script>
</head>
<body>
	<header class="site-header" id="header">
		<h1 class="site-header__title" data-lead-id="site-header-title">THANK YOU!</h1>
	</header>

	<div class="main-content">
		<i class="fa fa-check main-content__checkmark" id="checkmark"></i>
		<p class="main-content__body" data-lead-id="main-content-body">Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being you.</p>
	</div>

	<li><br> <br><a class="theme_btn tp_one" href="{% url 'landingpage:index' %}">Back to Home</a></li>

	<footer class="site-footer" id="footer">
		
	</footer>
</body>
</html>

{% endblock %}