TugasKelompok1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('accounts/', include('accounts.urls')),
    path('feedback/', include('main.urls')),
    path('kisahcovid/', include('kisahCovid.urls')),
    path('volunteer/',include('Vol.urls')),
    path('donasi/',include('donasi.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vol/urls.py
from django.urls import path

from . import views

app_name = 'Vol'

urlpatterns = [
    path('', views.home, name='home'),
    path('tambah-rumah-sakit/', views.tambahRumahSakit, name='rumahsakit'),
    path('tambah-volunteer/<int:id>', views.volunteer, name='volunteer'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
    path('home/',views.home,name='home')
]

donasi/urls.py
from django.urls import path
from .views import donasi, tambah_donasi, ajax_donasi, ajax_form

app_name = "Donasi"

urlpatterns = [
    path('', donasi, name="donasi"),
    path('form/', tambah_donasi, name='form'),
    path('form/ajax/', ajax_form, name='ajaxForm'),
    path('ajax/', ajax_donasi, name='ajax')


]

kisahCovid/urls.py
from django.urls import path
from .views import submit_kisah

app_name = 'kisahCovid'

urlpatterns = [
    path('', submit_kisah, name = 'kisahcovid'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.feedback_view, name='feedback'),
]

templates/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
   <head>
      <meta charset="utf-8">

      <!-- Responsive -->
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
      <title>Epicmed</title>
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      <!---------favicon--------------->
      <link rel="icon" type="image/png" href="{% static 'image/favicon-32x32.png' %}" sizes="32x32">
      <link rel="icon" type="image/png" href="{% static 'image/favicon-16x16.png' %}" sizes="16x16">
      <!---------stylesheet--------------->
      <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
      <!---------stylesheet addition--------------->
      <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
      <!---------stylesheet addition--------------->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
      <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css"> 
   </head>

   <body class="scroll_bar_style_one">

   <header class="header_v1">
      <!--Header-v1--->
      <section class="navbar_outer">
         <div class="navbar navbar-expand-lg  bsnav bsnav-sticky bsnav-sticky-slide">
            <div class="container">
               <a class="navbar-brand" href="{% url 'landingpage:index' %}"><img src="{% static 'image/epicmed.png' %}" class="img-fluid" alt="img"></a>
               <button class="navbar-toggler toggler-spring"><span class="navbar-toggler-icon"></span></button>
               <div class="collapse navbar-collapse scroll-nav" id="navbarnav">
                  <ul class="navbar-nav navbar-mobile navbar_left  ml-auto">
                     <li class="nav-item"><a class="nav-link link_hd" href="{% url 'landingpage:index' %}">Home </a></li>
                     <li class="nav-item"><a class="nav-link link_hd" href="{% url 'kisahCovid:kisahcovid' %}">Kisah Covid</a></li>
                     <li class="nav-item"><a class="nav-link link_hd" href="{% url 'main:feedback' %}">Feedback</a> </li>
                     <li class="nav-item"><a class="nav-link link_hd" href="{% url 'Vol:home' %}">Volunteer</a> </li>
                     <li class="nav-item"><a class="nav-link link_hd" href="{% url 'Donasi:donasi' %}">Donasi</a> </li>
                  </ul>
                  

                  <ul class="navbar-nav navbar-mobile navbar_right">
                     {% if user.is_authenticated %}
                     <div class="user-button">
                        <li><a class="theme_btn tp_one" href="{% url 'accounts:logout' %}">Logout</a></li>
                     </div>
                     {% else %}
                        <li><a class="theme_btn tp_one" href="{% url 'accounts:login' %}">Login</a></li>
                     {% endif %}
                  </ul>
                  
               </div>
            </div>
         </div>
         <!--Header-v1-end-->
      </section>
   </header>
   <!--Header-->

   {% block content %}
   {% endblock %}

   {% block extra_script %}
   {% endblock extra_script %}

   <!-----------footerlast UNWELL?--------------->
   <section class="footerlast type_one  pdb_80 pdt_80">
      <div class="container">
         <div class="row">
            <!---------row----------->
            <div class="col-lg-12 col-md-12  text-center">
               <!---------col----------->
               <div class="footer_last_box">
                  <div class="logo_footer">
                     <img src="{% static 'image/epicmed.png' %}" class="img-fluid" alt="img" />
                  </div>
                  <ul>
                     <li style="color:white;">© Copyright 2020 Team Semangat PPW</li>
                  <p  class="side-menu__block__text site-footer__copy-text">Developed with <span class="linearicons-heart"></span> by<small><a href="#"> Semangat PPW </a></small></p>
               </div>
               <!---------col-end---------->
            </div>
            <!----------row-end---------->
         </div>
      </div>
   </section>


   <!-----------------------------------script--------------------------->
   <script src="../static/js/all.js"></script> 
   <script src="../static/js/custom.js"></script>
   <script src="https://cdn.linearicons.com/free/1.0.0/svgembedder.min.js"></script>
   
</body>

</html>

templates/newnavbar.html
{% load static %}
<nav class="navbar">
    <div class="navbar-right">
        {% if user.is_authenticated %}
        <div class="user-button">
            <div class="user-header">
                <img src="#" class="user-menu-avatar">
                {{user.first_name}}
                <i class="fas fa-angle-down"></i>
            </div>
            <div class="user-menu collapse">
                <a href="#"><i class="fas fa-shopping-cart"></i> Cart</a>
                <a onclick="signOut()"><i class="fas fa-sign-out-alt"></i> Logout</a>
                <div class="google-sign-in-hide">
                    <div class="g-signin2" data-onsuccess="onSignIn"></div>
                </div>
            </div>
        </div>
        {% else %}
        <a href="/auth/">
            <button class="nav-login-button">
                Login
            </button>
        </a>
        {% endif %}
    </div>
</nav>
<script>
    $(document).ready(function(){
        $('.user-button').on('click', function(){
            if($('.user-menu').hasClass('collapse')){
                $('.user-menu').removeClass('collapse');
            }else{
                $('.user-menu').addClass('collapse');
            }
        });

        
    })

    function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function () {
          window.location.replace("/auth/logout/");
        });
      }
    
</script>