TugasKelompok1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('accounts/', include('accounts.urls')),
    path('feedback/', include('main.urls')),
    path('kisahcovid/', include('kisahCovid.urls')),
    path('volunteer/',include('Vol.urls')),
    path('donasi/',include('donasi.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vol/urls.py
from django.urls import path

from . import views

app_name = 'Vol'

urlpatterns = [
    path('', views.home, name='home'),
    path('tambah-rumah-sakit/', views.tambahRumahSakit, name='rumahsakit'),
    path('tambah-volunteer/<int:id>', views.volunteer, name='volunteer'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
    path('home/',views.home,name='home')
]

Vol/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Volunteer(models.Model):
    nama_Volunteer = models.CharField(max_length=100)
    KTP = models.CharField(max_length=100)
    alasan = models.TextField()
    class Meta:
        ordering = ['nama_Volunteer']

class RumahSakit(models.Model):
    nama_Rumah_Sakit = models.CharField(max_length=100)
    alamat = models.CharField(max_length=300)
    telepon = models.CharField(max_length=100)
    gambar = models.ImageField(upload_to='images/', null=True, blank=True)
    volunteer = models.ManyToManyField(Volunteer)
    class Meta:
        ordering = ['nama_Rumah_Sakit']

    def absolute_url(self):
        return reverse("Vol:volunteer", kwargs = {"id" : self.id})

Vol/forms.py
from django import forms
from .models import Volunteer, RumahSakit

class FormRumahSakit(forms.ModelForm) :
    class Meta:
        model = RumahSakit
        fields = [
            'nama_Rumah_Sakit',
            'alamat',
            'telepon',
            'gambar',
        ]

        widgets = {
            'nama_Rumah_Sakit' : forms.TextInput(attrs={'class' : 'form-control'}),
            'alamat' : forms.TextInput(attrs={'class' : 'form-control'}),
            'telepon' : forms.NumberInput(attrs={'class' : 'form-control'}),
        }

class FormVolunteer(forms.ModelForm) :
    class Meta:
        model = Volunteer
        fields = [
            'nama_Volunteer',
            'KTP',
            'alasan',
        ]

        widgets = {
            'nama_Volunteer' : forms.TextInput(attrs={'class' : 'form-control'}),
            'KTP' : forms.TextInput(attrs={'class' : 'form-control'}),
            'alasan' : forms.Textarea(attrs={'class' : 'form-control', 'rows':4}),
        }

Vol/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import RumahSakit, Volunteer
from .forms import FormRumahSakit, FormVolunteer
from django.http import HttpResponseRedirect
from django.http import JsonResponse

def home(request):
    tRumahSakit = RumahSakit.objects.all()
    data = {}
    form = FormRumahSakit(request.POST, request.FILES)

    # if (request.is_ajax()):
    #     form = FormRumahSakit(request.POST, request.FILES)
    #     if(form.is_valid()):
    #         form.save()
    #         data['nama'] = form.cleaned_data.get('nama_Rumah_Sakit')
    #         data['alamat'] = form.cleaned_data.get('alamat')
    #         data['telepon'] = form.cleaned_data.get('telepon')
    #         data['gambar'] = form.cleaned_data.get('gambar') 
    #         return JsonResponse(data)
    
    # if request.method == "POST":
    #     form = FormRumahSakit(request.POST, request.FILES)
    #     if form.is_valid():
    #         form.save()
    #         return redirect("/")

    context = {
        "rumahsakit" : tRumahSakit,
        "form" : form
    }
    return render(request, 'home.html', context)

def tambahRumahSakit(request,*args, **kwargs):
    namaRumahSakit = request.GET.get('nama_rumah_sakit ')
    alamatRumahSakit = request.GET.get('alamat ')
    teleponRumahSakit = request.GET.get('telepon ')
    gambarRumahSakit = request.GET.get('gambar ')


    RumahSakitBaru = RumahSakit.objects.create(nama_Rumah_Sakit = namaRumahSakit, alamat = alamatRumahSakit, telepon = teleponRumahSakit, gambar = gambarRumahSakit)
    
    data = []
    
    for dataBaru in RumahSakit.objects.all():
        dataJson = {}

        dataJson["nama"] = dataBaru.nama_Rumah_Sakit
        dataJson["alamat"] = dataBaru.alamat
        dataJson["telepon"] = dataBaru.telepon
        dataJson["gambar"] = dataBaru.gambar
        dataJson["jumlah"] = dataBaru.volunteer.objects.count()
        dataJson["volunteerRS"] = dataBaru.absolute_url()

        data.append(dataJson)

    return JsonResponse(data)
    

def volunteer(request, *args, **kwargs):
    form = FormVolunteer()

    if request.method == "POST":
        nama_Volunteer = request.POST.get("nama_Volunteer")
        KTP = request.POST.get("KTP")
        alasan = request.POST.get("alasan")
        volunteerDaftar = Volunteer.objects.create(nama_Volunteer = nama_Volunteer, KTP = KTP, alasan = alasan)
        rumahsakit = RumahSakit.objects.get(id = kwargs["id"])
        rumahsakit.volunteer.add(volunteerDaftar)
        return redirect("/volunteer/")
    
    
    context = {
        "form" : form,
    }

    return render(request, "tambahVolunteer.html", context)

Vol/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<style>
  .card{
    background-color: #ededed;
    color: black;
  }

  #card{
    background-color: #ededed;
    color: black;
    transition: transform 0.01s;
  }

  #card:hover{
    transform: scale(1.01);
  }

  #table{
    color: black;
  }

  #judul {
    padding-top: 100px;
    font-size: 48px;
    font-weight: 1000;
    background: linear-gradient(90deg, rgba(121,119,180,1) 0%, rgba(155,152,255,1) 38%, rgba(72,217,202,1) 84%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    line-height: 52px;
  }
  
</style>
</head>
<h1 class="text-center mb-5" id="judul">Volunteer</h1>

<div class="container">
  <div class="row">
    
    {% for rs in rumahsakit %}
    <div class="col mb-4 ml-4" id="barisan">
      <div class="card p-0 shadow rounded" id="card" style="width: 18rem; border: solid 2px #48d9ca;">
        <img src="{{rs.gambar.url}}" class="card-img-top" alt="{{rs.nama_Rumah_Sakit}}" style="height: 11rem;">
        <div class="card-body">
          <h5 class="card-title text-center mt-0 mb-0" id="card-title">{{rs.nama_Rumah_Sakit}}</h5>
          <table class="table table-borderless mt-1 mb-1" id="table">
            <tbody>
              <tr>
                <th scope="row" class="pt-1"><i class="fa fa-map-marker" aria-hidden="true"></i></th>
                <td class="pt-1">{{rs.alamat}}</td>
              </tr>
              <tr>
                <th scope="row" class="pt-1"><i class="fa fa-phone" aria-hidden="true"></i></th>
                <td class="pt-1">{{rs.telepon}}</td>
              </tr>      
              <tr>
                <th scope="row" class="pt-1"><i class="fa fa-user" aria-hidden="true"></i></th>
                <td class="pt-1">{{rs.volunteer.all|length}} Volunteer</td>
              </tr>
            </tbody>
          </table>
          
          <!-- {% if user.is_authenticated %} -->
          <div class="text-center">
            <a href="{{rs.absolute_url}}" class="btn btn-primary text-center">Daftar Volunteer</a>
          </div>
          <!-- {% else %}
          <div class="text-center">
            <a href="{% url 'accounts:login' %}" class="btn btn-primary text-center">Daftar Volunteer</a>
          </div>
          {% endif %}     -->
        </div>
      </div>
    </div>  
    {% endfor %}

    <div class="modal" id="mymodel" style="top: 10%;">
      <div class="container p-3 modal-content" style="background-color: #48d9ca; color: white;">
        <div class="modal-header">
          <h1 class="white" style="margin-left: 34%;">Daftar Rumah Sakit</h1>
          <button type="button" class="close" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i></button>
        </div>
        <br>
          {{ form.as_p }}
          <div class="col-md-12 text-center">
              <button class="btn btn-primary btn-lg" id="tombolSubmit">Tambah</button>
          </div>
      </div>
    </div>
  
    {% if user.is_authenticated %}
    <div class="col-12 col-md-12 btn-row text-center mb-2">
      <a class="theme_btn tp_one" data-target="#mymodel" data-toggle="modal">Tambah Rumah Sakit</a> 
      <br>
      <br>
    </div>
    {% else %}
    <div class="col-12 col-md-12 btn-row text-center mb-2">
      <a href="{% url 'accounts:login' %}" class="theme_btn tp_one">Tambah Rumah Sakit</a> 
      <br>
      <br>
    </div>
    {% endif %}
  </div>
</div>

<script>
  $(document).ready(function(){
    $("#tombolSubmit").click(function(){
      var nama = $("#id_nama_Rumah_Sakit").val();
      var alamat = $("#id_alamat").val();
      var telepon = $("#id_telepon").val();
      var gambar = "https://www.google.com/url?sa=i&url=http%3A%2F%2Fhospital.umm.ac.id%2Fpage%2Fsejarah.html&psig=AOvVaw2_MtHmnC5LUvS-tQ2DvIPF&ust=1609683879325000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNjN9fG5_e0CFQAAAAAdAAAAABAE"

      $.ajax({
        url: "tambah-rumah-sakit?nama_rumah_sakit =" + nama + "&alamat =" + alamat + "&telepon = " + telepon + "&gambar = " + gambar + "/",
        dataType: "json", 
        success: function (response) {
          var obj_hasil = response;
          var buatKartu = $("#barisan")
          $("#barisan").empty

          
          
          for (i = 0; i < obj_hasil.length; i++) {
            buatKartu.append("<div class='card p-0 shadow rounded' id='card' style='width: 18rem; border: solid 2px #48d9ca;'>")
            buatKartu.append("<img src='" + obj_hasil[i]["gambar"] + "'" + " class='card-img-top' alt='" + obj_hasil[i].nama + "'" + " style='height: 11rem;'>")
            buatKartu.append("<div class='card-body'>")
            buatKartu.append("<h5 class='card-title text-center mt-0 mb-0' id='card-title'>" + obj_hasil[i]["nama"] + "</h5>")
            buatKartu.append("<table class='table table-borderless mt-1 mb-1' id='table'>")
            buatKartu.append("<tbody>")
            buatKartu.append("<tr>")
            buatKartu.append("<th scope='row' class='pt-1'><i class='fa fa-map-marker' aria-hidden='true'></i></th>")
            buatKartu.append("<td class='pt-1'>" + obj_hasil[i]["alamat"] + "</td>")
            buatKartu.append("</tr>")
            buatKartu.append("<tr>")
            buatKartu.append("<th scope='row' class='pt-1'><i class='fa fa-phone' aria-hidden='true'></i></th>")
            buatKartu.append("<td class='pt-1'>" + obj_hasil[i]["telepon"] + "</td>")
            buatKartu.append("</tr>")
            buatKartu.append("<tr>")
            buatKartu.append("<th scope='row' class='pt-1'><i class='fa fa-user' aria-hidden='true'></i></th>")
            buatKartu.append("<td class='pt-1'>" + obj_hasil[i]["jumlah"] + "</td>")
            buatKartu.append("</tr>")
            buatKartu.append("</tbody>")
            buatKartu.append("</table>")
            buatKartu.append("<div class='text-center'>")
            buatKartu.append("<a href='" + obj_hasil[i]["volunteerRS"] + "'" + " class'btn btn-primary text-center'>Daftar Volunteer</a>")
            buatKartu.append("</div>")
            buatKartu.append("</div>")
            buatKartu.append("</div>")
          }
        }
      });
    })
  })
</script>

<!-- script buat bootstrap -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
{% endblock content %}

Vol/templates/tambahRS.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<style>
    h1 {
        padding-top: 100px;
        font-size: 48px;
        font-weight: 1000;
        background: linear-gradient(90deg, rgba(121,119,180,1) 20%, rgba(155,152,255,1) 38%, rgba(72,217,202,1) 84%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        line-height: 52px;
  }

</style>
</head>
<h1 class="text-center mb-3">Tambah Rumah Sakit</h1>
    <div class="container p-3 mt-5 mb-5" style="background-color: #48d9ca; color: white;">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="row">
                <div class="col-4 col-sm-1">
                    <input class="btn btn-primary" type="submit" value="Tambah">
                </div>
                <div class="col-6 col-sm-1">
                    <a href="{% url 'Vol:home' %}" class="btn btn-danger">Kembali</a>
                </div>
            </div>
        </form>
    </div>
<!-- script buat bootstrap -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
{% endblock content %}

Vol/templates/tambahVolunteer.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<style>
    h1 {
        padding-top: 100px;
        font-size: 48px;
        font-weight: 1000;
        background: linear-gradient(90deg, rgba(121,119,180,1) 20%, rgba(155,152,255,1) 38%, rgba(72,217,202,1) 84%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        line-height: 52px;
  }

</style>
</head>
<h1 class="text-center mb-3">Tambah Volunteer</h1>
    <div class="container p-3 mt-5 mb-5" style="background-color: #48d9ca; color: white;">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="row">
                <div class="col-4 col-sm-1">
                    <input class="btn btn-primary" type="submit" value="Daftar">
                </div>
                <div class="col-6 col-sm-1">
                    <a href="{% url 'Vol:home' %}" class="btn btn-danger">Kembali</a>
                </div>
            </div>
        </form>
    </div>
<!-- script buat bootstrap -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
{% endblock content %}